In [2]:
# Assigning features and label variables
# First Feature
color= ['Red','Red','Orange','Red','Green','Red','Red','Green','Green','Red',
        'Green','Red','Red','Red','Red','Red','Orange','Red','Orange','Red','Red',
        'Red','Red','Green','Orange','Red','Green','Green','Red','Red']
# Second Feature
weight=['70','100','28','3','100','100','3','70','70','7',
        '27','7','28','7','70','27','28','3','28','7','100',
        '3','7','70','28','7','28','100','27','27']
# Third Feature
size= ['Small','Big','Medium','Small','Big','Big','Small','Small','Small','Small',
        'Medium','Small','Medium','Small','Small','Medium','Medium','Small','Medium','Small',
        'Big','Small','Small','Small','Medium','Small','Medium','Big','Medium','Medium']

In [3]:
# Label or target varible
fruits=['Apple','Apple','Plums','Cherry','Apple','Apple','Cherry','Apple','Apple','Cherry',
        'Plums','Cherry','Plums','Cherry','Apple','Plums','Plums','Cherry','Plums','Cherry',
        'Apple','Cherry','Cherry','Apple','Plums','Cherry','Plums','Apple','Plums','Plums']

<div class="alert alert-block alert-warning">
<b>Data Preprocessing:</b> Lable Encoding
</div>


|Color|LabelEncoder|
|-----|------------|
|Green|0|
|Orange|1|
|Red|2|

In [6]:
# Import LabelEncoder
from sklearn import preprocessing

#creating labelEncoder
le = preprocessing.LabelEncoder()

# Converting string labels into -numbers.
color_encoded = le.fit_transform(color)

print("Orginal Data",color)
print("Lable Encoder",color_encoded)
# 0 - Green
# 1- Orange
# 2 - Red

Orginal Data ['Red', 'Red', 'Orange', 'Red', 'Green', 'Red', 'Red', 'Green', 'Green', 'Red', 'Green', 'Red', 'Red', 'Red', 'Red', 'Red', 'Orange', 'Red', 'Orange', 'Red', 'Red', 'Red', 'Red', 'Green', 'Orange', 'Red', 'Green', 'Green', 'Red', 'Red']
Lable Encoder [2 2 1 2 0 2 2 0 0 2 0 2 2 2 2 2 1 2 1 2 2 2 2 0 1 2 0 0 2 2]


|Lable_Encoded|Size|
|---------|---|
|2| Small|
|1| Medium|
|0| Big|

In [7]:
size_encoded=le.fit_transform(size)
print(size)
print(size_encoded)

# 2 - Small
# 1 - Medium
# 0 - Big

['Small', 'Big', 'Medium', 'Small', 'Big', 'Big', 'Small', 'Small', 'Small', 'Small', 'Medium', 'Small', 'Medium', 'Small', 'Small', 'Medium', 'Medium', 'Small', 'Medium', 'Small', 'Big', 'Small', 'Small', 'Small', 'Medium', 'Small', 'Medium', 'Big', 'Medium', 'Medium']
[2 0 1 2 0 0 2 2 2 2 1 2 1 2 2 1 1 2 1 2 0 2 2 2 1 2 1 0 1 1]


|Lable_Encoded|Fruits|
|---------|---|
|0|Apple| 
|2|Plums|
|1|Cherry|


In [8]:
#target or label
label=le.fit_transform(fruits)
print(fruits)
label
# Apple - 0
# Plums - 2
# Cherry - 1

['Apple', 'Apple', 'Plums', 'Cherry', 'Apple', 'Apple', 'Cherry', 'Apple', 'Apple', 'Cherry', 'Plums', 'Cherry', 'Plums', 'Cherry', 'Apple', 'Plums', 'Plums', 'Cherry', 'Plums', 'Cherry', 'Apple', 'Cherry', 'Cherry', 'Apple', 'Plums', 'Cherry', 'Plums', 'Apple', 'Plums', 'Plums']


array([0, 0, 2, 1, 0, 0, 1, 0, 0, 1, 2, 1, 2, 1, 0, 2, 2, 1, 2, 1, 0, 1,
       1, 0, 2, 1, 2, 0, 2, 2], dtype=int64)

In [10]:
import numpy as np

#combining color weight and size into  single list of tuples
features=list(zip(color_encoded,weight,size_encoded))

features = np.array(features,dtype=np.float)
features

array([[  2.,  70.,   2.],
       [  2., 100.,   0.],
       [  1.,  28.,   1.],
       [  2.,   3.,   2.],
       [  0., 100.,   0.],
       [  2., 100.,   0.],
       [  2.,   3.,   2.],
       [  0.,  70.,   2.],
       [  0.,  70.,   2.],
       [  2.,   7.,   2.],
       [  0.,  27.,   1.],
       [  2.,   7.,   2.],
       [  2.,  28.,   1.],
       [  2.,   7.,   2.],
       [  2.,  70.,   2.],
       [  2.,  27.,   1.],
       [  1.,  28.,   1.],
       [  2.,   3.,   2.],
       [  1.,  28.,   1.],
       [  2.,   7.,   2.],
       [  2., 100.,   0.],
       [  2.,   3.,   2.],
       [  2.,   7.,   2.],
       [  0.,  70.,   2.],
       [  1.,  28.,   1.],
       [  2.,   7.,   2.],
       [  0.,  28.,   1.],
       [  0., 100.,   0.],
       [  2.,  27.,   1.],
       [  2.,  27.,   1.]])

In [11]:
from sklearn.neighbors import KNeighborsClassifier

model = KNeighborsClassifier(n_neighbors=3,metric='euclidean')

# Train the model using the training sets
model.fit(features,label)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='euclidean',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [13]:
model.classes_

array([0, 1, 2], dtype=int64)

In [15]:
#predicting the fruit
predicted= model.predict([[1,2,1]]) 
print(predicted)

[1]


In [16]:
model.score(features,label)

1.0

In [22]:
from sklearn.neighbors import KNeighborsClassifier

model = KNeighborsClassifier(n_neighbors=4)

# Train the model using the training sets
model.fit(features,label)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=4, p=2,
                     weights='uniform')

In [23]:
model.classes_

array([0, 1, 2], dtype=int64)

In [24]:
#predicting the fruit
predicted= model.predict([[1,2,1]]) 
print(predicted)

[1]


In [25]:
model.score(features,label)

1.0