# Mushroom dataset

Adjusting Key Performance Indicators

In [1]:
import pandas as pd
import numpy as np

mush_df = pd.read_csv('Data/mushrooms.csv')
mush_df

class cap-shape cap-surface cap-color bruises odor gill-attachment  \
0        p         x           s         n       t    p               f   
1        e         x           s         y       t    a               f   
2        e         b           s         w       t    l               f   
3        p         x           y         w       t    p               f   
4        e         x           s         g       f    n               f   
...    ...       ...         ...       ...     ...  ...             ...   
8119     e         k           s         n       f    n               a   
8120     e         x           s         n       f    n               a   
8121     e         f           s         n       f    n               a   
8122     p         k           y         n       f    y               f   
8123     e         x           s         n       f    n               a   

     gill-spacing gill-size gill-color  ... stalk-surface-below-ring  \
0               c         n          k  ...                        s   
1               c         b          k  ...                        s   
2               c         b          n  ...                        s   
3               c         n          n  ...                        s   
4               w         b          k  ...                        s   
...           ...       ...        ...  ...                      ...   
8119            c         b          y  ...                        s   
8120            c         b          y  ...                        s   
8121            c         b          n  ...                        s   
8122            c         n          b  ...                        k   
8123            c         b          y  ...                        s   

     stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
0                         w                      w         p          w   
1                         w                      w         p          w   
2                         w                      w         p          w   
3                         w                      w         p          w   
4                         w                      w         p          w   
...                     ...                    ...       ...        ...   
8119                      o                      o         p          o   
8120                      o                      o         p          n   
8121                      o                      o         p          o   
8122                      w                      w         p          w   
8123                      o                      o         p          o   

     ring-number ring-type spore-print-color population habitat  
0              o         p                 k          s       u  
1              o         p                 n          n       g  
2              o         p                 n          n       m  
3              o         p                 k          s       u  
4              o         e                 n          a       g  
...          ...       ...               ...        ...     ...  
8119           o         p                 b          c       l  
8120           o         p                 b          v       l  
8121           o         p                 b          c       l  
8122           o         e                 w          v       l  
8123           o         p                 o          c       l  

[8124 rows x 23 columns]

In [2]:
mush_df_encoded = pd.get_dummies(mush_df)
mush_df_encoded

class_e  class_p  cap-shape_b  cap-shape_c  cap-shape_f  cap-shape_k  \
0           0        1            0            0            0            0   
1           1        0            0            0            0            0   
2           1        0            1            0            0            0   
3           0        1            0            0            0            0   
4           1        0            0            0            0            0   
...       ...      ...          ...          ...          ...          ...   
8119        1        0            0            0            0            1   
8120        1        0            0            0            0            0   
8121        1        0            0            0            1            0   
8122        0        1            0            0            0            1   
8123        1        0            0            0            0            0   

      cap-shape_s  cap-shape_x  cap-surface_f  cap-surface_g  ...  \
0               0            1              0              0  ...   
1               0            1              0              0  ...   
2               0            0              0              0  ...   
3               0            1              0              0  ...   
4               0            1              0              0  ...   
...           ...          ...            ...            ...  ...   
8119            0            0              0              0  ...   
8120            0            1              0              0  ...   
8121            0            0              0              0  ...   
8122            0            0              0              0  ...   
8123            0            1              0              0  ...   

      population_s  population_v  population_y  habitat_d  habitat_g  \
0                1             0             0          0          0   
1                0             0             0          0          1   
2                0             0             0          0          0   
3                1             0             0          0          0   
4                0             0             0          0          1   
...            ...           ...           ...        ...        ...   
8119             0             0             0          0          0   
8120             0             1             0          0          0   
8121             0             0             0          0          0   
8122             0             1             0          0          0   
8123             0             0             0          0          0   

      habitat_l  habitat_m  habitat_p  habitat_u  habitat_w  
0             0          0          0          1          0  
1             0          0          0          0          0  
2             0          1          0          0          0  
3             0          0          0          1          0  
4             0          0          0          0          0  
...         ...        ...        ...        ...        ...  
8119          1          0          0          0          0  
8120          1          0          0          0          0  
8121          1          0          0          0          0  
8122          1          0          0          0          0  
8123          1          0          0          0          0  

[8124 rows x 119 columns]

In [3]:
X_mush = mush_df_encoded.iloc[:,2:]
y_mush = mush_df_encoded.iloc[:,1]

In [4]:
X_mush.head()

cap-shape_b  cap-shape_c  cap-shape_f  cap-shape_k  cap-shape_s  \
0            0            0            0            0            0   
1            0            0            0            0            0   
2            1            0            0            0            0   
3            0            0            0            0            0   
4            0            0            0            0            0   

   cap-shape_x  cap-surface_f  cap-surface_g  cap-surface_s  cap-surface_y  \
0            1              0              0              1              0   
1            1              0              0              1              0   
2            0              0              0              1              0   
3            1              0              0              0              1   
4            1              0              0              1              0   

   ...  population_s  population_v  population_y  habitat_d  habitat_g  \
0  ...             1             0             0          0          0   
1  ...             0             0             0          0          1   
2  ...             0             0             0          0          0   
3  ...             1             0             0          0          0   
4  ...             0             0             0          0          1   

   habitat_l  habitat_m  habitat_p  habitat_u  habitat_w  
0          0          0          0          1          0  
1          0          0          0          0          0  
2          0          1          0          0          0  
3          0          0          0          1          0  
4          0          0          0          0          0  

[5 rows x 117 columns]

In [5]:
y_mush.head()

0    1
1    0
2    0
3    1
4    0
Name: class_p, dtype: uint8

In [9]:
from sklearn.svm import SVC
from sklearn.model_selection import validation_curve

* If you Data is `Linearly Separable` we use Linear Kernal(LR,KNN,DT,NB)
* if you Data is Non-Linearly Separable then we have to Use Kernal is SVM('rbf','linear','polynomial','sigmoid').
**or**
* if you Data is Non-Linearly Separable then we can Convert them into linear Transformation we can apply(LR,KNN,DT,NB).

![](https://lh3.googleusercontent.com/-vuIFlxlno0U/Xw0ruoFLG5I/AAAAAAAApCY/09bYRBY5rbQcNq9KnPCJkgN9q9lKMA-6gCK8BGAsYHg/s0/2020-07-13.png)


In [7]:
np.logspace(-4, 1, 7)

array([1.00000000e-04, 6.81292069e-04, 4.64158883e-03, 3.16227766e-02,
       2.15443469e-01, 1.46779927e+00, 1.00000000e+01])

In [15]:
def getTrainingAndTestScores():
    train_scores, valid_scores = validation_curve(SVC(kernel='rbf', C=1, random_state=0), X_mush, y_mush,
                                                  param_name="gamma",
                                                  scoring="accuracy"
                                                  param_range=np.logspace(-4, 1, 6),
                                                  verbose=3)
    train_scores = np.mean(train_scores, axis=1)
    valid_scores = np.mean(valid_scores, axis=1)
    return (train_scores, valid_scores)

training, test = getTrainingAndTestScores()

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


[CV] gamma=0.0001 ....................................................
[CV] .... gamma=0.0001, score=(train=0.939, test=0.730), total=   4.9s
[CV] gamma=0.001 .....................................................


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    8.0s remaining:    0.0s


[CV] ..... gamma=0.001, score=(train=0.979, test=0.733), total=   1.3s
[CV] gamma=0.01 ......................................................


[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:   10.2s remaining:    0.0s


[CV] ...... gamma=0.01, score=(train=0.998, test=0.786), total=   0.7s
[CV] gamma=0.1 .......................................................
[CV] ....... gamma=0.1, score=(train=1.000, test=0.842), total=   2.1s
[CV] gamma=1.0 .......................................................
[CV] ....... gamma=1.0, score=(train=1.000, test=0.810), total=  12.0s
[CV] gamma=10.0 ......................................................
[CV] ...... gamma=10.0, score=(train=1.000, test=0.518), total=   9.3s
[CV] gamma=0.0001 ....................................................
[CV] .... gamma=0.0001, score=(train=0.876, test=0.971), total=   6.2s
[CV] gamma=0.001 .....................................................
[CV] ..... gamma=0.001, score=(train=0.982, test=0.993), total=   2.7s
[CV] gamma=0.01 ......................................................
[CV] ...... gamma=0.01, score=(train=0.999, test=0.999), total=   0.7s
[CV] gamma=0.1 .......................................................
[CV] .

[Parallel(n_jobs=1)]: Done  30 out of  30 | elapsed:  3.9min finished


In [16]:
print("Training Score: ")
print(training)
print("Testing  scores: ")
print(test)
print("on Different Gamma")
print(np.logspace(-4, 1, 6))

Training Score: 
[0.89826487 0.98270541 0.99858441 1.         1.         1.        ]
Testing  scores: 
[0.88749928 0.84192338 0.85422031 0.89386222 0.85594005 0.51797143]
on Different Gamma
[1.e-04 1.e-03 1.e-02 1.e-01 1.e+00 1.e+01]


In [8]:
def getGammaValues():
    gamma = np.logspace(-4, 1, 6)
    return (gamma[0], gamma[5], gamma[3])

underfit, overfit, good_generalization = getGammaValues()

print("Underfitting value")
print(underfit)
print("Overfitting value")
print(overfit)
print("Good fit")
print(good_generalization)

Underfitting value
0.0001
Overfitting value
10.0
Good fit
0.1
